// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.22.3
// source: api/proto/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash of uri
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Date and time to remind the storage
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_api_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Page) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Page) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// The request message containing body.
type StoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Api   string                 `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Page entity to add
	Page          *Page `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_api_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StoreRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *StoreRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// The response message containing body
type StoreReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Api           string                 `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReply) Reset() {
	*x = StoreReply{}
	mi := &file_api_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReply) ProtoMessage() {}

func (x *StoreReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReply.ProtoReflect.Descriptor instead.
func (*StoreReply) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StoreReply) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

// The request message
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// Tre replay message
type GetReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Result        bool                   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplay) Reset() {
	*x = GetReplay{}
	mi := &file_api_proto_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplay) ProtoMessage() {}

func (x *GetReplay) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplay.ProtoReflect.Descriptor instead.
func (*GetReplay) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetReplay) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetReplay) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type LenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LenRequest) Reset() {
	*x = LenRequest{}
	mi := &file_api_proto_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LenRequest) ProtoMessage() {}

func (x *LenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LenRequest.ProtoReflect.Descriptor instead.
func (*LenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{5}
}

type LenReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LenReplay) Reset() {
	*x = LenReplay{}
	mi := &file_api_proto_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LenReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LenReplay) ProtoMessage() {}

func (x *LenReplay) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LenReplay.ProtoReflect.Descriptor instead.
func (*LenReplay) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{6}
}

func (x *LenReplay) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_api_proto_storage_proto protoreflect.FileDescriptor

const file_api_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/storage.proto\x12\astorage\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n" +
	"\x04Page\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"C\n" +
	"\fStoreRequest\x12\x10\n" +
	"\x03api\x18\x01 \x01(\tR\x03api\x12!\n" +
	"\x04page\x18\x02 \x01(\v2\r.storage.PageR\x04page\"\x1e\n" +
	"\n" +
	"StoreReply\x12\x10\n" +
	"\x03api\x18\x01 \x01(\tR\x03api\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"7\n" +
	"\tGetReplay\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06result\x18\x02 \x01(\bR\x06result\"\f\n" +
	"\n" +
	"LenRequest\"#\n" +
	"\tLenReplay\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length2\xa4\x01\n" +
	"\aStorage\x125\n" +
	"\x05Store\x12\x15.storage.StoreRequest\x1a\x13.storage.StoreReply\"\x00\x120\n" +
	"\x03Get\x12\x13.storage.GetRequest\x1a\x12.storage.GetReplay\"\x00\x120\n" +
	"\x03Len\x12\x13.storage.LenRequest\x1a\x12.storage.LenReplay\"\x00B\rP\x01Z\t.;storageb\x06proto3"

var (
	file_api_proto_storage_proto_rawDescOnce sync.Once
	file_api_proto_storage_proto_rawDescData []byte
)

func file_api_proto_storage_proto_rawDescGZIP() []byte {
	file_api_proto_storage_proto_rawDescOnce.Do(func() {
		file_api_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_storage_proto_rawDesc), len(file_api_proto_storage_proto_rawDesc)))
	})
	return file_api_proto_storage_proto_rawDescData
}

var file_api_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_storage_proto_goTypes = []any{
	(*Page)(nil),                  // 0: storage.Page
	(*StoreRequest)(nil),          // 1: storage.StoreRequest
	(*StoreReply)(nil),            // 2: storage.StoreReply
	(*GetRequest)(nil),            // 3: storage.GetRequest
	(*GetReplay)(nil),             // 4: storage.GetReplay
	(*LenRequest)(nil),            // 5: storage.LenRequest
	(*LenReplay)(nil),             // 6: storage.LenReplay
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_api_proto_storage_proto_depIdxs = []int32{
	7, // 0: storage.Page.createdAt:type_name -> google.protobuf.Timestamp
	0, // 1: storage.StoreRequest.page:type_name -> storage.Page
	1, // 2: storage.Storage.Store:input_type -> storage.StoreRequest
	3, // 3: storage.Storage.Get:input_type -> storage.GetRequest
	5, // 4: storage.Storage.Len:input_type -> storage.LenRequest
	2, // 5: storage.Storage.Store:output_type -> storage.StoreReply
	4, // 6: storage.Storage.Get:output_type -> storage.GetReplay
	6, // 7: storage.Storage.Len:output_type -> storage.LenReplay
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_storage_proto_init() }
func file_api_proto_storage_proto_init() {
	if File_api_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_storage_proto_rawDesc), len(file_api_proto_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_storage_proto_goTypes,
		DependencyIndexes: file_api_proto_storage_proto_depIdxs,
		MessageInfos:      file_api_proto_storage_proto_msgTypes,
	}.Build()
	File_api_proto_storage_proto = out.File
	file_api_proto_storage_proto_goTypes = nil
	file_api_proto_storage_proto_depIdxs = nil
}
